### ISSUE TITLE
Write tests for these methods

### ISSUE THREAD

**Issue by FindlayMB** [seng438-winter-2024/seng438-a3-FindlayMB#1]
These methods are missing tests completely.

The files for unique methods (methods that don't overload another method) have been created.

## DataUtilities

- `boolean equal(double[][] a, double[][] b)`  **100% coverage**
- `double[][] clone(double[][] source)` **100% coverage**
- `double calculateColumnTotal(Values2D data, int column, int[] validRows)` **91.7% coverage**
- `double calculateRowTotal(Values2D data, int row, int[] validCols)` **91.7% coverage**

For calculateColumnTotal and calculateRowTotal 91.7% is the max coverage possible since there is code is impossible to run.

## Range

- `double getLength()` **Max coverage**
- `double getCentralValue()` **Max coverage**
- `boolean intersects(Range range)` **100% coverage**
- `Range combineIgnoringNaN(Range range1, Range range2)` **100% coverage**
- `Range expand(Range range, double lowerMargin, double upperMargin)` **100% coverage**
- `Range shift(Range base, double delta)` **100% coverage**
- `Range shift(Range base, double delta, boolean allowZeroCrossing)` **100% coverage**
- `Range scale(Range base, double factor)` **100% coverage**
- `boolean isNaNRange()` **100% coverage**
- `int hashCode() `**100% coverage**
- `boolean equals(Object obj)` **100% coverage**
- Helper functions
  - `double min(double d1, double d2)`
  - `double max(double d1, double d2)`
  - `double shiftWithNoZeroCrossing(double value, double delta)`

**Comment by nick-c-garcia** [comment]
added test function: combine_Range2IsNull()
100% coverage for combine function

**Comment by saraaah-qin** [comment]
- getLength() - unable to get 100% coverage, please check inline comments
- getCentralValue() - 100% coverage
- intersect(Range range) - 100% coverage
- dont need min and max because they are helper functions

**Comment by FindlayMB** [comment]
`boolean equal(double[][] a, double[][] b)` - 100% coverage

**Comment by nick-c-garcia** [comment]
Scale function 100% coverage
- null range covers first line
- negative factor covers if statement
- 0 and positive covers rest of function


Tests made:
- scale_NullRange
- scale_ValidRangeNegativeFactor
- scale_ValidRangeZeroFactor
- scale_ValidRangePositiveFactor
- scale_ValidRangePositiveFactorMAX

**Comment by saraaah-qin** [comment]
expand(Range, double, double) - 100%
- null range covers IllegalArgumentException
- basic case covers everything but if statement
- negative margins covers if statement

Tests made:
- noRangeShouldThrowIllegalException()
- basicCase()
- maxPercentage()
- overMaxPercentage()
- zeroPercentageCase()
- negativeMargins()

**Comment by FindlayMB** [comment]
`double[][] clone(double[][] source)` - 100% coverage
- Need to add comments for the tests.

**Comment by nick-c-garcia** [comment]
Shift functions 100% coverage
 - null range covers IllegalArgumentException
 - tests 2-6 cover shift where allowZeroCrossing is true
      - used positive, negative, 0, max, and min for delta for coverage
 - tests 7-11 cover shift where allowZeroCrossing is false
      -  used multiple ranges for coverage of if statements in the shift helper function

Tests made:
 - shiftWithIllegalRange()
 - allowZeroCrossing is true
      - positiveRangeShift()
      - maxValueRangeShift()
      - negativeRangeShift()
      - minValueRangeShift()
      - zeroRangeShift()
 - allowZeroCrossing is false
      - positiveRangeShiftUBNoZeroCrossing()
      - positiveRangeShiftBothBoundsNoZeroCrossing()
      - negativeRangeShiftLBNoZeroCrossing()
      - negativeRangeShiftBothBoundsNoZeroCrossing()
      - rangeShiftBothBoundsAreZeroNoZeroCrossing()

**Comment by nick-c-garcia** [comment]
CombineIgnoringNaN function 100% coverage

- combinations of null, NaN, and vaild ranges for if statement coverage

Tests made: 
- ignoringNaNTwoNullRangesReturnsNull()
- ignoringNaNRange1NullReturnsRange2()
- ignoringNaNRange2NullReturnsRange1()
- ignoringNaNTwoNaNRangesReturnsNull()
- ignoringNaNRange1NaNReturnsRange2()
- ignoringNaNRange2NaNReturnsRange1()
- ignoringNaNRange1NaNRange2NullReturnsNull()
- ignoringNaNRange2NaNRange1NullReturnsNull()
- ignoringNaNBothRangesAreValidReturnsCombinedRange()

**Comment by nick-c-garcia** [comment]
Equals function 100% coverage
- used null, non Range objects and Range objects with different bounds for if statement coverage

Tests made:
- equalsNull()
- equalsNonRangeObject()
- equalsRangeObject()
- notEqualsLBRangeObject()
- notEqualsUBRangeObject()
- notEqualsBothBoundsRangeObject()

**Comment by nick-c-garcia** [comment]
IsNaNRange function 100% coverage
- is only one line, tests are boundary level

Tests made:
- validRangeIsNotNaNRange()
- LBNaNRangeIsNotNaNRange()
- UBNaNRangeIsNotNaNRange()
- NaNRangeIsNaNRange()

Hashcode function 100% coverage
- all lines can be covered in one test

Test made:
- calculatesAndReturnsHashcodeForRange()

**Comment by FindlayMB** [comment]
Assignment was completed and achieved a grade of 100%.
